//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicaciones_Web.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class FotosEmpleado
    {
        public int IdFoto { get; set; }
        public string idEmpleado { get; set; }
        public string NombreFoto { get; set; }

        [JsonIgnore]
        public virtual EMPLeado EMPLeado { get; set; }
    }
}
